## Random sampling with numpy

In [1]:
import numpy as np
import random

In [10]:
np.random.random(1)

array([0.6367649])

In [11]:
np.random.random((3,3))

array([[0.36726572, 0.94301353, 0.51825299],
       [0.2505081 , 0.32399617, 0.8986968 ],
       [0.63517129, 0.53892939, 0.19199946]])

In [19]:
np.random.randint(1,4,(4,4))

array([[2, 2, 3, 3],
       [2, 3, 1, 1],
       [2, 2, 3, 1],
       [2, 1, 3, 1]])

In [26]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 1, 2],
        [3, 2, 1, 3],
        [2, 3, 1, 1],
        [2, 3, 2, 2]],

       [[1, 1, 1, 1],
        [2, 2, 2, 3],
        [1, 3, 3, 1],
        [1, 3, 1, 1]]])

In [28]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [29]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [35]:
np.random.rand(3)

array([0.83198977, 0.30977806, 0.59758229])

In [36]:
np.random.rand(3,3)

array([[0.87239246, 0.98302087, 0.46740328],
       [0.87574449, 0.2960687 , 0.13129105],
       [0.84281793, 0.6590363 , 0.5954396 ]])

In [37]:
np.random.randn(3,3)

array([[-1.96711722e+00, -8.70956667e-01, -1.10682548e+00],
       [ 2.75123658e-01, -3.64456144e-01, -1.16515347e+00],
       [-1.34306988e+00,  1.45339286e+00,  1.16944865e-03]])

In [38]:
x = [1,2,3,4]

In [41]:
np.random.choice(x)

2

In [45]:
for i in range (1,10):
  print(np.random.choice(x))

2
2
3
1
3
2
1
2
2


In [46]:
x

[1, 2, 3, 4]

In [47]:
np.random.permutation(x)

array([3, 4, 2, 1])