In [1]:
import numpy as np

In [2]:
mx_1 = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
mx_1 = np.ones((3,4))
print(mx_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
mx_1 = np.ones((3,4), dtype=int)
print(mx_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
mx_1 = np.zeros((3,4))
print(mx_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
mx_1 = np.zeros((3,4),dtype=bool)
print(mx_1)

[[False False False False]
 [False False False False]
 [False False False False]]


In [13]:
mx_1 = np.zeros((3,4),dtype=str)
print(mx_1)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [22]:
em = np.empty((3,3))
print(em)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
