In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
arr_2d = np.array([[1,2,3],[5,6,7]])

In [3]:
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.ndim

1

In [6]:
print(arr_2d)

[[1 2 3]
 [5 6 7]]


In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
arr_2d.ndim

2

In [9]:
arr_2d.size

6

In [10]:
arr_2d.shape

(2, 3)

In [11]:
arr_2d.dtype

dtype('int64')